micronaut:
  application:
    name: dfm-biblioteca-publica-api
  server:
    port: 8080
    netty:
      max-header-size: 8192
  http:
    client:
      read-timeout: 30s

datasources:
  default:
    url: jdbc:mysql://localhost:3306/biblioteca
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: biblioteca_user
    password: Di131928*
    dialect: MYSQL
    auto: update

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        connection:
          CharSet: utf8mb4
          characterEncoding: utf8mb4

logger:
  levels:
    root: INFO
    com.dfm.biblioteca: DEBUG
    io.micronaut.http: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jackson:
  serialization:
    indent-output: true
    write-dates-as-timestamps: false
    default-view: com.dfm.biblioteca.presentation.view.EntityView

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false